### ISSUE TITLE
BatchResult.record incorrectly typed as B instead of AerospikeRecord<B>

### ISSUE THREAD

**Issue by jefflembeck** [aerospike/aerospike-client-nodejs#802]
**Describe the bug**
The record property on BatchResult in typings/index.d.ts is typed as B (the bins type) instead of AerospikeRecord<B>. This contradicts the actual runtime behavior and causes type errors when accessing result.record.bins.

**To Reproduce**
```typescript
import Aerospike, { AerospikeBins } from 'aerospike';

const client = await Aerospike.connect(config);

const batchKeys = keys.map((key) => ({
    type: Aerospike.batchType.BATCH_READ,
    key: new Aerospike.Key(namespace, set, key),
    readAllBins: true,
}));

const results = await client.batchRead(batchKeys);

// TypeScript error when accessing record.bins
const bins = results
    .map((row) => row.record.bins)
    .filter((c: AerospikeBins | undefined) => !!c);
```

Error message:

```
TS2769: No overload matches this call.
  Overload 1 of 2, '(predicate: (value: AerospikeBinValue, ...) => value is AerospikeBins, ...)', gave the following error.
    Types of parameters 'c' and 'value' are incompatible.
      Type 'AerospikeBinValue' is not assignable to type 'AerospikeBins | undefined'.
        Type 'null' is not assignable to type 'AerospikeBins | undefined'.
```

The underlying issue is that `row.record` is typed as `AerospikeBins`, so `row.record.bins` returns `AerospikeBinValue` (via the string index signature) instead of the actual bins object.

**Expected behavior**
BatchResult.record should be typed as `AerospikeRecord<B>`, allowing `result.record.bins` to return `B` (the bins object).

The runtime implementation in [lib/commands/batch_command.js](https://github.com/aerospike/aerospike-client-nodejs/blob/master/lib/commands/batch_command.js#L36) confirms this:

```javascript
const record = new Record(result.key, result.bins, result.meta)
return new BatchResult(result.status, record, result.inDoubt)
```

At runtime, record is a Record instance (i.e., AerospikeRecord) constructed with key, bins, and meta — not just the bins object directly.

**Versions and Environment (please complete the following information):**
 - Client application OS: MacOS 15
 - Aerospike Client Version: 6.3.0/6.4.0
 - Aerospike Database Version: N/A

**Comment by DomPeliniAerospike** [comment]
Hi @jefflembeck,
Thank you for the detailed issue report.
This will be fixed in the next release, 6.5.0.  I am aiming to publish today, and I will send another message when the update is complete.

**Comment by DomPeliniAerospike** [comment]
Hi @jefflembeck,

I released Node.js Client 6.5.0, which should resolve this issue.

Closing the issue, but feel free to reopen if needed.

**Comment by bit0r1n** [comment]
Not fixed yet. In pull request there is only fix for the constructor, but error also appears on class field type
https://github.com/aerospike/aerospike-client-nodejs/blob/60ff981aede89ba35717ddd7c694a093f2870571/typings/index.d.ts#L838-L842

**Comment by DomPeliniAerospike** [comment]
Hi @bit0r1n,
Creating a patch release to fix this, will notify when release is complete.

**Comment by DomPeliniAerospike** [comment]
Hi @bit0r1n @jefflembeck,
Just released [6.5.1](https://github.com/aerospike/aerospike-client-nodejs/releases/tag/v6.5.1). I added the correction the `BatchResult` definition and added testing to confirm the new changes compiles and works as necessary.
Apologies for missing this correction in the first release.
Going to close this issue again, feel free to reopen if needed.
